import { generateResumeBase64, generateCoverLetterBase64, generateLinkedInBase64 } from './pdf';

export async function sendResumeEmail({ toEmail, generatedData, formData, userName }) {
  const serviceId = import.meta.env.VITE_EMAILJS_SERVICE_ID;
  const templateId = import.meta.env.VITE_EMAILJS_TEMPLATE_ID;
  const publicKey = import.meta.env.VITE_EMAILJS_PUBLIC_KEY;

  // Generate PDF base64 content
  const resumeB64 = generateResumeBase64(generatedData.resume, userName, formData?.jobRole || '', formData);
  const coverB64 = generateCoverLetterBase64(generatedData.coverLetter);
  const linkedinB64 = generateLinkedInBase64(generatedData.linkedinAbout);

  // If EmailJS is configured, send via EmailJS with PDF attachments
  if (serviceId && templateId && publicKey) {
    if (!window.emailjs) {
      await new Promise((resolve, reject) => {
        const s = document.createElement('script');
        s.src = 'https://cdn.jsdelivr.net/npm/@emailjs/browser@4/dist/email.min.js';
        s.onload = resolve;
        s.onerror = reject;
        document.body.appendChild(s);
      });
      window.emailjs.init(publicKey);
    }

    return window.emailjs.send(serviceId, templateId, {
      to_email: toEmail,
      user_name: userName,
      resume_text: generatedData.resume,
      cover_letter_text: generatedData.coverLetter,
      linkedin_text: generatedData.linkedinAbout,
      resume_pdf: resumeB64,
      cover_letter_pdf: coverB64,
      linkedin_pdf: linkedinB64,
    });
  }

  // Fallback: open mailto with resume content in body
  return sendViaMailto(toEmail, userName, generatedData);
}

function sendViaMailto(toEmail, userName, generatedData) {
  const subject = encodeURIComponent(`Your HireReady AI Resume — ${userName}`);
  const body = encodeURIComponent(
    `Hi ${userName},\n\nHere are your HireReady AI documents:\n\n` +
    `━━━ RESUME ━━━\n\n${generatedData.resume}\n\n` +
    `━━━ COVER LETTER ━━━\n\n${generatedData.coverLetter}\n\n` +
    `━━━ LINKEDIN ABOUT ━━━\n\n${generatedData.linkedinAbout}\n\n` +
    `Generated by HireReady AI — https://hirereadyai.in`
  );

  const mailtoUrl = `mailto:${toEmail}?subject=${subject}&body=${body}`;

  // Try to open mailto — works on all devices
  const a = document.createElement('a');
  a.href = mailtoUrl;
  a.target = '_blank';
  a.click();

  return Promise.resolve('mailto');
}
